import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Kauri Kallaste</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            lorem ipsum lmao
        </div>
    )
}

export default Home
